[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Handle SPA routing - fallback to index.html for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (if needed later)
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/download-cv"
  to = "/.netlify/functions/download-cv"
  status = 200